// <auto-generated />
namespace NTU_FYP_REBUILD_17.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatedAssignedGame : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedAssignedGame));
        
        string IMigrationMetadata.Id
        {
            get { return "201908031226104_updatedAssignedGame"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
